import { IProduct } from "models/product.model";

export const ProductData: IProduct[] = [
  {
    id: 1,
    name: "Product 1",
    price: "200",
    description: "Product 1 description",
    categoryId: 1,
    subCategoryId: 1,
    imagePath:
      "https://a0.muscache.com/im/pictures/014df369-194e-47b1-9d5e-197a22ea9f40.jpg?im_w=720",
    images: [],
    rating: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: new Date(),
  },
  {
    id: 2,
    name: "Product 2",
    price: "3000",
    description: "Product 2 description",
    categoryId: 2,
    subCategoryId: 2,
    imagePath:
      "https://a0.muscache.com/im/pictures/e386d60e-d902-4589-aefb-1943eb7947c3.jpg?im_w=720",
    images: [],
    rating: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: new Date(),
  },
  {
    id: 3,
    name: "Product 3",
    price: "450",
    description: "Product 3 description",
    categoryId: 3,
    subCategoryId: 3,
    imagePath:
      "https://a0.muscache.com/im/pictures/90b74311-6f55-41ea-8649-e0556b5c3e3e.jpg?im_w=720",
    images: [],
    rating: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: new Date(),
  },
  {
    id: 4,
    name: "Product 4",
    price: "6000",
    description: "Product 4 description",
    categoryId: 4,
    subCategoryId: 4,
    imagePath:
      "https://a0.muscache.com/im/pictures/miso/Hosting-45465864/original/3d966c94-4c87-479b-8eeb-4889e9fb6ac9.jpeg?im_w=720",
    images: [],
    rating: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: new Date(),
  },
  {
    id: 5,
    name: "Product 5",
    price: "700",
    description: "Product 5 description",
    categoryId: 5,
    subCategoryId: 5,
    imagePath:
      "https://a0.muscache.com/im/pictures/08e56940-5521-4bce-9929-f99e2aba446f.jpg?im_w=720",
    images: [],
    rating: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: new Date(),
  },
  {
    id: 6,
    name: "Product 6",
    price: "900",
    description: "Product 6 description",
    categoryId: 6,
    subCategoryId: 6,
    imagePath:
      "https://a0.muscache.com/im/pictures/20d6aec2-0334-4923-8b20-6ad0c6d75aa3.jpg?im_w=720",
    images: [],
    rating: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: new Date(),
  },
  {
    id: 7,
    name: "Product 7",
    price: "1000",
    description: "Product 7 description",
    categoryId: 7,
    subCategoryId: 7,
    imagePath:
      "https://a0.muscache.com/im/pictures/d987ff62-d4be-49e8-a762-428ae79b24af.jpg?im_w=720",
    images: [],
    rating: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: new Date(),
  },
  {
    id: 8,
    name: "Product 8",
    price: "250",
    description: "Product 8 description",
    categoryId: 8,
    subCategoryId: 8,
    imagePath:
      "https://a0.muscache.com/im/pictures/de7f6d3c-0658-4e73-84d9-a756b496594b.jpg?im_w=720",
    images: [],
    rating: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: new Date(),
  },
  {
    id: 9,
    name: "Product 9",
    price: "10000",
    description: "Product 9 description",
    categoryId: 9,
    subCategoryId: 9,
    imagePath:
      "https://a0.muscache.com/im/pictures/miso/Hosting-551942747953724626/original/67cc46b1-740c-4f85-8c04-1029be045bb7.jpeg?im_w=720",
    images: [],
    rating: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: new Date(),
  },
];
